// Fade Up Per Word
if(!__fb_layers || !__fb_layers.length) throw "No layers";
var L = __fb_layers[0];
var ip = L.inPoint;
var dur = Math.max(L.outPoint - ip, 0.5);
var txt = L.property("Source Text").value;
var ot = txt.text;
var esc = ot.replace(/\\/g,"\\\\").replace(/"/g,'\\"').replace(/\n/g,"\\n");
var words = ot.split(/\s+/);
var cnt = words.length || 1;
var fx = L.property("ADBE Effect Parade").addProperty("ADBE Slider Control");
fx.name = "FadeUpWord";
fx.property("Slider").setValueAtTime(ip, 0);
fx.property("Slider").setValueAtTime(ip + dur, cnt);
L.property("Source Text").expression = 'var idx=Math.floor(effect("FadeUpWord")("Slider").value);var w="'+esc+'".split(/\\s+/);if(idx>w.length)idx=w.length;w.slice(0,idx).join(" ");';
var grp = L.property("ADBE Transform Group");
var op = grp.property("ADBE Opacity");
var pos = grp.property("ADBE Position");
var sv = pos.value;
op.setValueAtTime(ip, 0);
op.setValueAtTime(ip + dur*0.6, 100);
pos.setValueAtTime(ip, [sv[0], sv[1]+60]);
pos.setValueAtTime(ip + dur*0.6, sv);
for(var k=1;k<=op.numKeys;k++) op.setTemporalEaseAtKey(k,[new KeyframeEase(0,33.33)],[new KeyframeEase(0,33.33)]);
for(var k=1;k<=pos.numKeys;k++) pos.setTemporalEaseAtKey(k,[new KeyframeEase(0,33.33)],[new KeyframeEase(0,33.33)]);
